# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ead7b1feded484bf1ef2c63615038411"
name = "Welcome"
handle = "welcome-8"
application_url = "https://ebook-inquire-greetings-dam.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "newstorewdce.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ebook-inquire-greetings-dam.trycloudflare.com/auth/callback",
  "https://ebook-inquire-greetings-dam.trycloudflare.com/auth/shopify/callback",
  "https://ebook-inquire-greetings-dam.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
